### ISSUE TITLE
Searching SQKFechedTableViewController when section key path is provided causes crash.

### ISSUE THREAD

**Issue by steprescott** [3squared/SQKDataKit#19]
Subclass of SQKFechedTableViewController. When a section key path is provided to the fetched results controller via the delegate method `- (NSString *)sectionKeyPathForSearchableFetchedResultsController:(SQKFetchedTableViewController *)controller` it causes the crash below when a search is performed via the search bar.

```
*** Assertion failure in -[UITableViewRowData rectForRow:inSection:heightCanBeGuessed:], /SourceCache/UIKit_Sim/UIKit-2935.137/UITableViewRowData.m:1790
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for rect at invalid index path (<NSIndexPath: 0xc000000000008016> {length = 2, path = 0 - 1})'
```

Removing this delegate so no section key path is returned allows the searching to work but the data is then not in a desired layout.

**Comment by blork** [comment]
Any progress on this?

**Comment by blork** [comment]
There appears to be a problem when using a storyboard (I'm shocked).

Usually you register the cell class on the regular tableview, and then this is dequeued for both the regular and search tableviews. 

But in Ste's example, using storyboards, this crashes when trying to use a cell dequeued from tableview in the search tableview.

The solution is to also register the class or nib on the search tableview, and dequeue it from there,
