### ISSUE TITLE
Migration Manager

### ISSUE THREAD

**Issue by CaptainRedmuff** [3squared/SQKDataKit#41]
It would be handy to be able to pass in a migration manager when instantiating the context manager which is needed by the persistent store coordinator.

Content Manager -> Persistent Store Coordinator -> Migration Manager

If the persistent store coordinator returns false for `compatibleWithStoreMetadata`, then use the migration manager to resolve the issue either with lightweight migration or mapping models.

**Comment by blork** [comment]
Added in 6c14844c72c283dc8bba02933c997edab6ffb2e0.
