### ISSUE TITLE
Crash on `sqk_deleteAllObjectsInContext:error:`

### ISSUE THREAD

**Issue by Kodah** [3squared/SQKDataKit#46]
Crashes on [this line](https://github.com/3squared/SQKDataKit/blob/master/Classes/shared/NSManagedObject%2BSQKAdditions/NSManagedObject%2BSQKAdditions.m#L83), and prints:

```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
```

Remove these lines to fix the crash:

```
fetchRequest.includesPropertyValues = NO;
fetchRequest.returnsObjectsAsFaults = NO;
```

Should probably investigate why removing these lines fixes the crash before implementing the fix to avoid any unintended side affects.

**Comment by blork** [comment]
Cannot reproduce this bug :put_litter_in_its_place:.
