### ISSUE TITLE
Duplicate symbol error when installing Pod

### ISSUE THREAD

**Issue by steprescott** [3squared/SQKDataKit#56]
When installing the Pod and building the project it fails with a duplicate symbol error.

```
duplicate symbol _SQKDataKitErrorDomain in:
    /Users/steprescott/Library/Developer/Xcode/DerivedData/Electronic_Documents-aalbrwiiwalbxadguquokkjrzafx/Build/Products/Debug-iphonesimulator/libPods-SQKDataKit.a(SQKDataKitErrors-9B7492B116B7AE88.o)
ld: 5 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The issue is the Podspec of SQKDataKit including `'Classes/shared/SQKDataKitErrors.{h,m}'` in each subspec. It will work fine if you only require one subspec of the pod but when you simply install the pod it is included five times.

**Comment by blork** [comment]
Fixed by 3b2781450320ed6c7266b6507abd6a314bd5a731.
