### ISSUE TITLE
SQKCoreDataOperation should only save and merge the private context it created.

### ISSUE THREAD

**Issue by lukestringer90** [3squared/SQKDataKit#6]
When `completeOperationBySavingContext:` is called the `SQKCoreDataOperation` should check that the specified context is the same context as was created during the `start` method. 

A possible solution:

```
- (void)completeOperationBySavingContext:(NSManagedObjectContext *)managedObjectContext {
	if ([self isCancelled]) {
		[self finishOperation];
	}
        // Only save and merge the MOC that was made by this operation to start with
	else if (self.managedObjectContextToMerge == managedObjectContext) {
		[[NSNotificationCenter defaultCenter] addObserver:self
		                                         selector:@selector(contextSaveNotificationReceived:)
		                                             name:NSManagedObjectContextDidSaveNotification
		                                           object:nil];

		NSError *error = nil;
		[managedObjectContext save:&error];
		if (error) {
			NSLog(@"%@", error);
		}
	}
    else {
        [self finishOperation]
    }
}
```

**Comment by blork** [comment]
Isn't this accomplished in contextSaveNotificationReceived instead? At this line: https://github.com/3squared/SQKDataKit/blob/a820817dbb66165d14aa71dc0a57d21b6a326eef/Classes/shared/SQKCoreDataOperation/SQKCoreDataOperation.m#L137

it checks that `managedObjectContext == self.managedObjectContextToMerge` - doesn't that enforce this behaviour?

**Comment by lukestringer90** [comment]
Well spotted, it looks like this is checked else where so this is not necessary.

To address your previous comment regarding passing the managedObjectContext as being unnecessary: I agree and I think then method name should be changed. I'll close this issue and open a new one to discuss further.
