### ISSUE TITLE
`SQKCoreDataOperation` failing to complete

### ISSUE THREAD

**Issue by lukestringer90** [3squared/SQKDataKit#84]
Currently, `SQKCoreDataOperation` manages the merge of private context changes into the main context. In order to do this in a thread safe way semaphores are used:

1. `completeOperationBySavingContext:` called
2. Save the the private context own by the operation
3. On the current (background) thread create a semaphore.
4. On the main thread where the main context lives begin merge the changes.
5. On the background thread wait for the semaphore to be signalled.
6. On the main thread where the main complete then merge and signal the semaphore.
7. Receive signal and complete the operation.

There is a bug that prevents step 7 from happening, and the operation on the background thread never receives the semaphore signal from the main thread. This means the operation never completes.

**Comment by blork** [comment]
I think I can see several issues with SQKCoreDataOperation (regardless of the fix in #83)

1. `self.managedObjectContextToMerge` is reassigned on L96, despite this class being the one to own and manage that context. Why are we letting the user pass a context, when we've passed it to them on L67?
2. The operation registers for `NSManagedObjectContextDidSaveNotification` so it can call `finishOperation` later, but then `finishOperation` is called immediately anyway on L107.
3. The `start` method uses `performBlockAndWait` on L66, but this causes the queue to wait for the block to complete. This operation is meant to be asynchronous (i.e. `isConcurrent` = NO), so we could be using `performBlock`.

**Comment by lukestringer90** [comment]
Some good points. My replies:

1. I agree - this method is confusing and the operation should only ever be concerned with _it's_ MOC, so passing it as a method argument is unnecessary. I propose we the method name to `completeOperationBySavingContext` with no arguments.
2. If the save fails then the `NSManagedObjectContextDidSaveNotification` notification will not be received, and `finishOperation` will never get called. So it is called on L107 if the save fails.
3. My thoughts on this is that the operation executes asynchronously from the queues point of view, but all the code belonging to the operation should execute synchronously.

**Comment by blork** [comment]
2. Ah, it was reading it as `!error` 😩 
3. This makes sense, but I thought if `isConcurrent` is NO, then start should immediately return, doing everything in the background. More concerning is this snippet I just read:

> By default, this method returns NO, which means the operation runs synchronously in the calling thread.
> 
> If you want to implement a concurrent operation—that is, one that runs asynchronously with respect to the calling thread—you must write additional code to start the operation asynchronously.
https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationObjects/OperationObjects.html#//apple_ref/doc/uid/TP40008091-CH101-SW1

So maybe `isConcurrent` should be YES? I'm confused. Also it got replaced by `isAsynchronous` at some point which is doubly confusing me.

**Comment by blork** [comment]
Perhaps that's the cause of the issue? If it's not currently asynchronous, it gets to the end of `start` and assumes it's finished? So the Notification stuff ends up in an odd state.

**Comment by lukestringer90** [comment]
Interesting point. Can you try @blork's suggestion @CaptainRedmuff?

**Comment by CaptainRedmuff** [comment]
Changes made based on comments.

**Comment by lukestringer90** [comment]
Fixed in #85
